- hosts: localhost
  tasks:
  - name: install Git
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone ourrepo
    git: repo=https://github.com/shimib/ourrepo.git dest=~/ourrepo
  - name: clone petclinic
    git: repo=https://github.com/shimib/spring-petclinic.git dest=~/petclinic
